# the name of your track or event
name = "Breakthroughs in Computing Speaker Series"

# the name of the group organizing the event
org = "Protocol Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Juan Benet"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://breakthroughs-in-computing.labweek.io/"

# the start date of the event
date = "2022-10-24"

# how many days the event lasts (1 - N)
days = 4

# the event times (shows up in the event card)
times = "10/24 16:00 - 18:00, 10/25 - 10/27 18:00 - 20:00"

# the event venue name (will show up on the event card - TODO)
venueName = "10/24 [Convento do Beato](https://goo.gl/maps/2yDdwVSHfgs1mYhL7), 10/25 - 10/27 [SUD Lisboa](https://g.page/sudlisboa?share)"

# the event venue address (will show up on a map -- TODO)
# venueAddress = ""

# the max number of attendees of the event
attendees = ""


# these is unsued:
# tickets = ""

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
color="orange"

# A small logomark for the corner of the event (logomark image can be placed in "/website/public/logomarks")
logomark = "/logomarks/Protocol Labs.jpeg"

# a description of the event.
# will show up when the user clicks the event card.
description = """‍This event is part of the Breakthroughs in Computing Speaker Series, on how technology will shape society in the next 5 to 25 years. Hosted by Protocol Labs, this series runs every evening from Oct 24-27. It's designed to bring people together, sharing convivial drinks, thoughtful discussions, and new connections.  

Watch the recordings with [Allison Duetmann](https://www.youtube.com/watch?v=lBvkFZycXRQ), [Nick Bostrom](https://www.youtube.com/watch?v=VG8lanbnbwk), [Ahmed Ghappour](https://www.youtube.com/watch?v=qymQqf8UefU), [Max Tegmark](https://www.youtube.com/watch?v=_5ZxcxS3o3k), and [Adam Marblestone](Adam Marblestone)!
"""

# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
priority = 3

# if event has a livestream uncomment the following line
isLive = true
