# the name of your track or event
name = "FIL Lisbon Main Stage"

# the name of the group organizing the event
org = "Filecoin Foundation"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Florencia Barreiro"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://fil-lisbon.io/"

# the start date of the event
date = "2022-10-31"

# how many days the event lasts (1 - N)
days = 2

# the event times (shows up in the event card)
times = "10:30 - 19:30"

# the event venue name (will show up on the event card - TODO)
venueName = "[LX Factory](https://goo.gl/maps/RqP3B78vFktLzbkRA)"

# the event venue address (will show up on a map -- TODO)
venueAddress = "R. Rodrigues de Faria 103, 1300-501 Lisboa, Portugal"

# the max number of attendees of the event
attendees = ""

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Conference"]

# a color, to group key events visually. use sparingly
color="blue"

# A small logomark for the corner of the event
logomark = "/logomarks/FF.circle.png"

# a description of the event.
# will show up when the user clicks the event card.
description = """
Fil Lisbon Main Stage is a two-day event with insightful talks from top-notch speakers, panel discussions from the world's foremost Filecoin ecosystem participants and Web3 co-builders. Our unmatched speaker lineup will dive into Filecoin and Web3, taking you through the Filecoin world of FVM, NFTs, the metaverse, and beyond to be a part of the Web3 wave.

Watch the recordings [here](https://www.youtube.com/watch?v=vVg4m0aTYm8)!  
"""

# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
priority = 2

# if event has a livestream uncomment the following line
isLive = true
