# the name of your track or event
name = "Lurk Day"

# the name of the group organizing the event
org = "PL Outercore, Lurk Lab, Yatima, and Supranational"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@jpeg07"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://www.eventbrite.com/e/lurk-day-lurk-applications-nova-and-hardware-acceleration-tickets-434021147937"

# the start date of the event
date = "2022-10-28"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "13:00 - 18:30"

# the event venue name (will show up on the event card - TODO)
venueName = "[Brotéria Café](https://goo.gl/maps/BTYadfHPD9UimKet8)"

# the event venue address (will show up on a map -- TODO)
venueAddress = "R. de São Pedro de Alcântara 3, 1200-365 Lisboa, Portugal"

# the max number of attendees of the event
attendees = ""


# these is unsued:
# tickets = ""

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Workshops","Happy Hour"]

# a color, to group key events visually. use sparingly
# color=""

# A small logomark for the corner of the event
logomark = "/logomarks/Lurk.jpeg"

# a description of the event.
# will show up when the user clicks the event card.
description = """
Lurk Day: Lurk, Applications, Nova, and Hardware Acceleration

Lurk is a Turing-complete language for recursive zk-SNARKs. This event will feature talks from Chhi'mèd Künzang (Protocol Labs and Lurk Lab), John Burnham (Yatima, Inc.), Marcin Grzybowski (Mutual Knowledge Systems), Srinath Setty (Microsoft Research), and Kelly Olson (Supranational).
 
Watch the recordings [here](https://www.youtube.com/playlist?list=PL1PBsckLPD1emZYnsBWTuDfC8B_0qkS1R)!

"""

# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
# priority =

isLive = true
