# the name of your track or event
name = "Filecoin Network Analytics Day"

# the name of the group organizing the event
org = "Starboard Ventures"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Sylvan Zhang"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://lu.ma/filecoin_network_analytics_day"

# the start date of the event
date = "2022-10-31"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "15:00-20:00"

# the event venue name (will show up on the event card - TODO)
venueName = "[Broteria](https://goo.gl/maps/TMJm7TZKUu8SQ5cDA)"

# the event venue address (will show up on a map -- TODO)
venueAddress = "R. de São Pedro de Alcântara 3, 1250-237 Lisboa, Portugal"

# the max number of attendees of the event
attendees = "All Welcome"


# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# A small logomark for the corner of the event (logomark image can be placed in "/website/public/logomarks")
logomark = "/logomarks/starboard.jpg"

# a description of the event.
# will show up when the user clicks the event card.
description = """
Join us as we dive into the network analytics that continuously spark conversations and inform network’s decisions.

On the Filecoin Network Analytics Day, you will hear insightful talks and discussions covering important topics on Filecoin network analytics, including:
  The importance of network analytics to Web3 governance and improvement
  Conducting effective network analytics for Filecoin - what's needed?
  Demystifying Filecoin circulating supply
  Analyzing key health metrics of Filecoin
  Storage provider reputation analytics
  And more...
"""

# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
priority = 3
